development:
  adapter: postgresql
  database: listodo_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: listodo_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: listodo_production
  pool: 5
  timeout: 5000
